### ISSUE TITLE
v1.7.1 is not available

### ISSUE THREAD

**Issue by arpanbag001** [AniTrend/android-emojify#108]
Version 1.7.1 (latest) is not available, as build failed https://jitpack.io/#wax911/android-emojify

Please rectify

**Comment by wax911** [comment]
Thanks @arpanbag001 working on this, I am away from home so will test this properly in 2 weeks time

**Comment by wax911** [comment]
Should be available now https://github.com/AniTrend/android-emojify/releases/tag/1.7.1
