### ISSUE TITLE
Typo in doc dependency

### ISSUE THREAD

**Issue by yoobi** [AniTrend/android-emojify#177]
## Description of Bug

```
dependencies {
    implementation 'com.github.anitrend:android-emojify:{latest_version}'
}
```
https://jitpack.io/#wax911/android-emojify --> 1.7.1 build successfully
https://jitpack.io/#AniTrend/android-emojify --> 1.7.1 build failed

README should be updated to either `com.github.wax911:android-emojify` or aniTrend should republish 1.7.1.

**Comment by wax911** [comment]
Thanks @yoobi PRs are always welcome 😃 I have just re-triggered a build https://jitpack.io/#anitrend/android-emojify/1.7.1 and should be available.

> https://jitpack.io/#wax911/android-emojify was where the project was initially hosted prior to moving it into the anitrend space, surprised it's still pulling from it

**Comment by yoobi** [comment]
If anitrend is the right repo to use then there is no typo in the doc :)
The only issue is that the build from https://jitpack.io/#anitrend/android-emojify/1.7.1 failed

**Comment by yoobi** [comment]
The build is successful now, you can close the issue :)
