### ISSUE TITLE
[Library][Manifest] android:allowBackup="true"

### ISSUE THREAD

**Issue by JonathanMercandalli** [AniTrend/android-emojify#2]
Do you really need that line in your lib manifest? (see your full manifest [here](https://github.com/wax911/android-emojify/blob/master/emojify/src/main/AndroidManifest.xml#L6))

```xml
android:allowBackup="true"
```
----

On client app, could be nice to use `android:allowBackup="false"` too. For now, here the compilation error if the client app do not use allowBackup.

```
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:16:9-36
  	is also present at [com.github.MatteoBattilana:WeatherView:2.0.2] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:15:5-35:19 to override.
```

----

Thks a lot for your lib =)

**Comment by wax911** [comment]
Hi, thanks. No that's not required at all, you can add `tools:replace="android:allowBackup` in you application tag to override the library configuration :)
